package com.github.ksoichiro.android.observablescrollview.samples;

// DO NOT EDIT: This file is automatically generated.
public class VersionInfo {
    public static final String LIBRARY_VERSION = "unknown";
    public static final String BUILD = "unknown";
}
